title: Day by Day Shae
description: Welcome, thank you for being here :)

permalink: /:title/
baseurl: ''
url: "https://daybydayshae.ca"
github_username: shaeplays

# Author Settings
author: Shae-Linn Davies 

# Build Settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# staticman comments configuration
staticman_url: https://bobert-9ef0825f876a.herokuapp.com/v2/entry/shaeplays/daybydayshae/main/comments

paginate: 8
paginate_path: "/page/:num"
